### ISSUE TITLE
Stuck at NVRAM.

### ISSUE THREAD

**Issue by TongDucThanhNam** [Lunarixus/Legion5-15ACH6H-macOS#1]
First of all, thank you very much for the instructions. However, unfortunately, I'm stuck at the **OpenCore boot picker** section it just have reset NVRAM there no MacOs installer.
I have completed the steps `Making the OpenCore USB` and `Making a macOS Installer`. In the USB installer, I only have two folders, `com.apple.recovery.boot` with two macOS installation files inside, and your folder named `EFI`. Then I enter the boot options, it only shows the option to `reset NVRAM`, and I cannot see the two Boot options for `Windows` nor `Ventura`. I'm not sure if I did something wrong. Also, could you tell me about that? Thanks again.
![PXL_20230727_181110648](https://github.com/Lunarixus/Legion5-15ACH6H-macOS/assets/96881214/0cee8cc6-d371-4db8-a117-fbfa714d2d95)

**Comment by TongDucThanhNam** [comment]
Update: 
Due to [this tutor](https://dortania.github.io/OpenCore-Install-Guide/troubleshooting/extended/opencore-issues.html#can-t-see-macos-partitions), i go to `config.plist` on **ScanPolicy** set to 0, now when i boot to `OpenCore boot picker` and press `space bar`, it will show `Ventura` after choice it, it go black screen and appear Apple's logo, then it has a progess bar but it only load 5% then it get full black screen doesn't have anything, after 10-15 minute, the device will restart.

**Comment by TongDucThanhNam** [comment]
Update: 
It appears that NootedRed caused some errors during the initial macOS installation. Consequently, I removed it and configured the installation of macOS first, and then used this EFI. Most of the features work fine, but unfortunately, the trackpad or touchpad is not functioning. The trackpad settings have completely disappeared from macOS settings, but we can use a mouse as an alternative. Despite these issues, I appreciate your efforts, and macOS is indeed very good. However, it seems to consume a significant amount of battery. Nevertheless, it remains a worthwhile choice to explore.

**Comment by mohit-saharia** [comment]
Hi @TongDucThanhNam can you tell me what you deleted for  NootedRed in config.plist file.

**Comment by TongDucThanhNam** [comment]
> Hi @TongDucThanhNam can you tell me what you deleted for NootedRed in config.plist file.

I just delete NootedRed.kext, seem we can't install macOS when have this. After install successful, we add NootedRed.kext to EFI to use AMD iGPU.

**Comment by mohit-saharia** [comment]
Hi @TongDucThanhNam 
for me it stuck on apple icon without progress bar can you tell me which version of ventura you are using.

**Comment by TongDucThanhNam** [comment]
> Hi @TongDucThanhNam 
> for me it stuck on apple icon without progress bar can you tell me which version of ventura you are using.

I'm using ventura 13.5 , have you remove NootedRed.kext by OCATool ?

**Comment by mohit-saharia** [comment]
No just removed kext from kexts folder and removed lines from config.plist file can you give me download link for OCATool.

**Comment by TongDucThanhNam** [comment]
> No just removed kext from kexts folder and removed lines from config.plist file can you give me download link for OCATool.

I think you should use EFI from this respository for install first https://github.com/kalkmann/Legion-5600H-Hackintosh. When you install successfully, then replace EFI.
