### ISSUE TITLE
Stuck At Apple Logo

### ISSUE THREAD

**Issue by thierrys6752** [Lunarixus/Legion5-15ACH6H-macOS#2]
hey @Lunarixus i selected install mac os ventura but its stuck at the apple logo.. can u please help me?

**Comment by TongDucThanhNam** [comment]
You need remove NootedRed.kext by OCATool first. After install macOs successful, add it again.

**Comment by thierrys6752** [comment]
I will test it now 1 sec

**Comment by thierrys6752** [comment]
@TongDucThanhNam I tried but its still stuck at the apple logo..
Is there any bios settings I have to change? Btw i have to eat so I'll be back in 2 hours ( hopefully )

**Comment by TongDucThanhNam** [comment]
> @TongDucThanhNam I tried but its still stuck at the apple logo..
> Is there any bios settings I have to change? Btw i have to eat so I'll be back in 2 hours ( hopefully )

Have you disable XHCI1 ? disable secure boot ?

**Comment by thierrys6752** [comment]
@TongDucThanhNam yep I disabled PXELAN but I don't have XHC1 btw

**Comment by thierrys6752** [comment]
@TongDucThanhNam yep I disabled PXELAN but I don't have xch1 btw but its still stuck

**Comment by TongDucThanhNam** [comment]
> @TongDucThanhNam yep I disabled PXELAN but I don't have xch1 btw but its still stuck

What is you device :?

**Comment by thierrys6752** [comment]
I think I have the problem

**Comment by thierrys6752** [comment]
@TongDucThanhNam I have the same device with all specifications but I have a Ryzen 7 5000 series and a GeForce RTX 3070

**Comment by TongDucThanhNam** [comment]
> @TongDucThanhNam I have the same device with all specifications but I have a Ryzen 7 5000 series and a GeForce RTX 3070

I think you should disable XHCI using advanced Bios like the guide.

**Comment by thierrys6752** [comment]
where is the advanced bios then @TongDucThanhNam

**Comment by TongDucThanhNam** [comment]
> where is the advanced bios then @TongDucThanhNam 
> 

In readme, there have Unlocking the advanced BIOS menu. Have you read the guide ?

**Comment by thierrys6752** [comment]
almost
gimme 1 sec

**Comment by thierrys6752** [comment]
@TongDucThanhNam I'm booting now

**Comment by thierrys6752** [comment]
i dont get it.. @TongDucThanhNam he gives an error if i boot the usb ( Omg i am so dumb.. )

**Comment by thierrys6752** [comment]
<img width="1077" alt="image" src="https://github.com/Lunarixus/Legion5-15ACH6H-macOS/assets/142600355/503e28f2-a9c6-4c7e-a977-c3a6fd599da1">

**Comment by thierrys6752** [comment]
<img width="1280" alt="image" src="https://github.com/Lunarixus/Legion5-15ACH6H-macOS/assets/142600355/d3d35d99-dff6-47b9-85ca-824234033898">

**Comment by thierrys6752** [comment]
<img width="1280" alt="image" src="https://github.com/Lunarixus/Legion5-15ACH6H-macOS/assets/142600355/8496869a-88c8-4da4-a830-2cb9fd7e8d52">

**Comment by thierrys6752** [comment]
i dont know where to put it :/

**Comment by TongDucThanhNam** [comment]
> i dont get it.. @TongDucThanhNam he gives an error if i boot the usb ( Omg i am so dumb.. )

😥 It should work, do you have telegram for easily contact.

**Comment by thierrys6752** [comment]
Yes i have

**Comment by thierrys6752** [comment]
@TongDucThanhNam  here: @Thijs6220

That's my telegram

**Comment by thierrys6752** [comment]
@TongDucThanhNam  My telegram worked?

**Comment by thierrys6752** [comment]
we couldnt find any issue thanks for helping me anyways @TongDucThanhNam
