### ISSUE TITLE
Trackpad not working

### ISSUE THREAD

**Issue by MinecraftNerrd1337** [Lunarixus/Legion5-15ACH6H-macOS#5]
Title says it all. I dog into it a little bit and it's a Synaptics trackpad, ID SYNA2BA6, working over I2C. My laptop is also a Legion 5 15ACH6H.
I tried so much stuff to get that trackpad working and just wasn't able to.

**Comment by MinecraftNerrd1337** [comment]
Anyone facing the same issue: do not use SSDT-HPET
Then it works even in interrupt. I don't remember if this EFI uses the right kexts, you might need to change them

**Comment by Lunarixus** [comment]
I've just seen this issue and I'm glad you found a fix, unfortunately this model of laptop despite having the same model number actually supports multiple trackpads, in my case I had an ELAN trackpad and will add this to the README, thanks.
